# Generated by Django 5.1 on 2024-09-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pollution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255)),
                ('iso', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('nitrogen_oxide', models.FloatField(help_text='Nitrogen oxide (NOx)')),
                ('sulphur_dioxide', models.FloatField(help_text='Sulphur dioxide (SO₂) emissions')),
                ('carbon_monoxide', models.FloatField(help_text='Carbon monoxide (CO) emissions')),
                ('organic_carbon', models.FloatField(help_text='Organic carbon (OC) emissions')),
                ('non_methane_volatile_organic_compounds', models.FloatField(help_text='Non-methane volatile organic compounds (NMVOC) emissions')),
                ('black_carbon', models.FloatField(help_text='Black carbon (BC) emissions')),
                ('ammonia', models.FloatField(help_text='Ammonia (NH₃) emissions')),
            ],
            options={
                'ordering': ['entity', 'year'],
                'indexes': [models.Index(fields=['entity'], name='air_polluti_entity_ed8ff1_idx'), models.Index(fields=['year'], name='air_polluti_year_ae7128_idx'), models.Index(fields=['entity', 'year'], name='air_polluti_entity_eeb373_idx')],
                'unique_together': {('entity', 'year')},
            },
        ),
    ]
